### PR TITLE
Feature/Travis CI configuration

### PR DESCRIPTION
**Pull request by dennisschroer**
This PR correctly sets up continuous integration with Travis by installing dependencies, building the application and executing the tests. It also adds build status to the README page.

Travis was already enabled (https://travis-ci.org/JHUISI/charm), but not correctly configured resulting in a build failure at all time (by default it attempts to test a ruby application). This also gives the (mostly) wrong indication that PRs are not correct.

### CODE REVIEW

**Comment by jakinyele** [comment]
Thank you!

**Comment by dennisschroer** [comment]
Wow that was quick :+1:

**Comment by jakinyele** [comment]
This has been on my todo list for quite awhile. So, very much appreciated!

**Comment by dennisschroer** [comment]
I see that is not quite correct now, https://travis-ci.org/JHUISI/charm/builds/139206275 fails but travis says it is succesful. Let me see if I can fix that

**Pull request merged**
