### PR TITLE
symcrypto.py: update to allow for AEAD

### PR DESCRIPTION
**Pull request by locksmithone**
Added the AEAD capability to symcrypto.py, i.e., it is possible to (optionally) specify additional data to be MACed together with the ciphertext. The additional data is typically a plaintext that will not be encrypted, but it is desired that this additional data be authenticated with the ciphertext. For instance, a header can be added to the ciphertext to be authenticated. Example of usage is included in the class docstring.

The module is backwards compatible with the previous AE (Authenticated Encryption) version with no additional data. All adapter classes that utilize symcrypto without additional data should continue working with no modifications.

### CODE REVIEW

**Review by jakinyele — CHANGES_REQUESTED** [review]
This is great, but a few change requests. Please clean up the paths in the doc test for AuthenticatedCryptoAbstraction and update the import on line 176 to charm.toolbox.symcrypto. Otherwise, the CI tests will fail after merge. Thanks again!

**Comment by locksmithone** [comment]
I have removed things from the doctest such that Travis CI stops throwing errors. But now Travis CI is complaining about unexpected EOLs in literals, whereas there are no visible EOLs in the doctest. I suspect Travis CI is wrapping lines, and thus inserting \n and that causes commands to break. I do not know how to fix that short of removing the doctest completely...

**Comment by jakinyele** [comment]
Ok, I agree that the line breaks are probably causing the CI errors now. You could just shorten like this to see if it makes a difference:
>>> aad = b'\x10\x11\x0a\x0b'
>>> cad = cipher.encrypt('Some network PDU.', additionalData=aad)

Superficial change but maybe that'll do the trick.

**Comment by locksmithone** [comment]
Ok, it seems Travis CI is ok with my relative paths in doctest.

**Comment by jakinyele** [comment]
Sorry to ask but do you mind submitting another PR for the 2.7-dev branch? Shouldn't require many changes though to work w/ 2.7. Thanks in advance!

**Comment by locksmithone** [comment]
Absolutely, let me work on that.

**Pull request merged**
