### PR TITLE
Abenc maabe rw15

### PR DESCRIPTION
**Pull request by dennisschroer**
This PR adds the implementation of "Efficient Statically-Secure Large-Universe Multi-Authority Attribute-Based Encryption" by Rouselakis and Waters. The (older) implementation on which it is based can be found [here](https://sites.google.com/site/yannisrouselakis/).

### CODE REVIEW

**Comment by artjomb** [comment]
Did you ask Rouselakis for a license? The scheme implementations on his site don't have a license (at least I haven't found one). Remember that unlicensed doesn't mean that it is in the public domain.

**Comment by jakinyele** [comment]
Good point. I've asked him and waiting on a reply.

**Comment by dennisschroer** [comment]
Good point, In a previous email he told me to feel free to modify it according to my needs, but I'm not sure if this means it can be published here. Lets wait for the reply

**Comment by jakinyele** [comment]
@artjomb @denniss17 I heard back from Yannis and he is OK with it. Thanks!

**Pull request merged**
