### PR TITLE
Revocable abe scheme yang

### PR DESCRIPTION
**Pull request by doughgle**
Improve testing and fix discovered bugs.

### CODE REVIEW

**Comment by jakinyele** [comment]
@doughgle having some issues on Py 2.7. Can you take a look? Error message below. Many thanks!
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <charm.test.schemes.abenc.abenc_yllc15_test.YLLC15Test testMethod=test_encrypt_proxy_decrypt_decrypt_round_trip>
    @settings(deadline=400, max_examples=50)
>   @given(policy_str=policy_expressions())
    def test_encrypt_proxy_decrypt_decrypt_round_trip(self, policy_str):
charm/test/schemes/abenc/abenc_yllc15_test.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/core.py:568: in execute
    result = self.test_runner(data, run)
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/executors.py:56: in default_new_style_executor
    return function(data)
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/core.py:566: in run
    return test(*args, **kwargs)
charm/test/schemes/abenc/abenc_yllc15_test.py:38: in test_encrypt_proxy_decrypt_decrypt_round_trip
    @given(policy_str=policy_expressions())
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/core.py:529: in test
    result = self.test(*args, **kwargs)
charm/test/schemes/abenc/abenc_yllc15_test.py:47: in test_encrypt_proxy_decrypt_decrypt_round_trip
    intermediate_value = self.abe.proxy_decrypt(self.params, skcs, proxy_key_user, ciphertext)
charm/toolbox/schemebase.py:165: in check_output
    output = func(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <charm.schemes.abenc.abenc_yllc15.YLLC15 object at 0x2aaf8a53e650>
params = {'e_gg_alpha': [24774654958147520887670374919037345720123656535680408065259589180252640681895...4969925962335203204936...921916242550774052716028531975551378...795881191560897057782849732760159257832758916380421025479640313513087369028303]}
skcs = 165887044702232454614227210360209009064479368905, proxy_key_user = None
ciphertext = None
    @Output(v_t)
    def proxy_decrypt(self, params, skcs, proxy_key_user, ciphertext):
>       policy_root_node = ciphertext['policy_str']
E       TypeError: 'NoneType' object has no attribute '__getitem__'
charm/schemes/abenc/abenc_yllc15.py:129: TypeError
----------------------------- Captured stdout call -----------------------------
invalid type: <type 'str'> not <type 'unicode'>
invalid '<type 'str'>' type for '2'
invalid type: <type 'str'> not <type 'unicode'>
invalid '<type 'str'>' type for '2'
invalid type: <type 'str'> not <type 'unicode'>
invalid '<type 'str'>' type for '2'
invalid type: <type 'str'> not <type 'unicode'>
invalid '<type 'str'>' type for '2'
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_encrypt_proxy_decrypt_decrypt_round_trip(self=<charm.test.schemes.abenc.abenc_yllc15_test.YLLC15Test testMethod=test_encrypt_proxy_decrypt_decrypt_round_trip>, policy_str=u'A')
You can reproduce this example by temporarily adding @reproduce_failure('4.7.9', 'AAABAAA=') as a decorator on your test case
=============== 1 failed, 179 passed, 5 skipped in 16.60 seconds ===============
make: *** [test] Error 1
The command "make test" exited with 2.

**Comment by doughgle** [comment]
@jakinyele Looks like a str vs unicode type error. Not sure how to fix it exactly. I'll try to take a look tomorrow evening...

**Comment by doughgle** [comment]
Hi @jakinyele, I tried to reproduce the error, but unfortunately I'm not able to build `2.7-dev` branch due to this error at `make test` stage:

`ImportError: /Storage/repos/tools/charm/charm/core/math/integer.so: undefined symbol: BN_is_negative`

I raised an issue for this last year -> https://github.com/JHUISI/charm/issues/194. If you can help me get past that, that will be progress towards reproducing and fixing the error on py2.7.

**Comment by jakinyele** [comment]
@doughgle Need to update the modules to support OpenSSL 1.1.1 as well. Looks like v1.0.2* is where `BN_is_negative` is still accessible. Will debug and commit a fix. Thanks!

**Comment by doughgle** [comment]
@jakinyele for 2.7-dev branch, need further help I'm afraid. I'm seeing this error at `make` stage.

```
building 'charm.core.math.integer' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DBENCHMARK_ENABLED=1 -Icharm/core/utilities/ -Icharm/core/benchmark/ -I/usr/include/python2.7 -c charm/core/math/integer/integermodule.c -o build/temp.linux-x86_64-2.7/charm/core/math/integer/integermodule.o
charm/core/math/integer/integermodule.c: In function ‘bnToMPZ’:
charm/core/math/integer/integermodule.c:130:6: error: dereferencing pointer to incomplete type ‘BIGNUM {aka struct bignum_st}’
  if(p->neg != 0) {
      ^
```
Seems like maybe the openssl headers are wrong, but I can't figure it out.

My `./configure` outputs:

```
$ ./configure.sh 
Install prefix    /usr/local
data directory    /usr/local/share/charm
binary directory  /usr/local/bin
library directory /usr/local/lib
config directory  /usr/local/etc
Source path       /media/dough/Storage/repos/tools/charm
CFLAGS            -O2 -g 
CHARM_CFLAGS       -m64 -Wall -Wundef -Wwrite-strings -Wmissing-prototypes  -fstack-protector-all -Wendif-labels -Wmissing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits
LDFLAGS           -m64 
make              make
python            /usr/bin/python
python-config     /usr/bin/python-config
build_ext options build_ext 
install           install
host CPU          x86_64
wget              /usr/bin/wget
gprof enabled     no
profiler          no
static build      no
-Werror enabled   no
integer module    yes
ecc module        yes
pairing module    yes
disable benchmark no
libm found        yes
libgmp found      yes
libpbc found      yes
libcrypto found   yes
Documentation     no
```

My `/usr/local/lib` looks like this:

```
$ ll /usr/local/lib/
total 56780
drwxr-xr-x  7 root root      4096 Mar  3 22:34 ./
drwxr-xr-x 10 root root      4096 Jul 20  2016 ../
drwxr-xr-x  2 root root      4096 Nov  3 23:11 engines-1.1/
-rwxr-xr-x  1 root root     42086 Aug  7  2018 libbswabe.a*
-rw-r--r--  1 root root   5683634 Nov  3 23:11 libcrypto.a
lrwxrwxrwx  1 root root        16 Nov  3 23:11 libcrypto.so -> libcrypto.so.1.1*
-rwxr-xr-x  1 root root   3369064 Nov  3 23:11 libcrypto.so.1.1*
-rw-r--r--  1 root root   1365086 Aug  7  2018 libgmp.a
-rwxr-xr-x  1 root root       913 Aug  7  2018 libgmp.la*
lrwxrwxrwx  1 root root        16 Aug  7  2018 libgmp.so -> libgmp.so.10.3.2*
lrwxrwxrwx  1 root root        16 Aug  7  2018 libgmp.so.10 -> libgmp.so.10.3.2*
-rwxr-xr-x  1 root root    536296 Aug  7  2018 libgmp.so.10.3.2*
-rw-r--r--  1 root root   1755472 Aug  3  2018 libgtest.a
-rw-r--r--  1 root root      3836 Aug  3  2018 libgtest_main.a
-rw-r--r--  1 root root  28441746 Aug  3  2018 libopenabe.a
-rwxr-xr-x  1 root root  10771328 Aug  3  2018 libopenabe.so*
-rw-r--r--  1 root root    557874 Mar  3 22:34 libpbc.a
-rwxr-xr-x  1 root root       942 Mar  3 22:34 libpbc.la*
lrwxrwxrwx  1 root root        15 Mar  3 22:34 libpbc.so -> libpbc.so.1.0.0*
lrwxrwxrwx  1 root root        15 Mar  3 22:34 libpbc.so.1 -> libpbc.so.1.0.0*
-rwxr-xr-x  1 root root    388608 Mar  3 22:34 libpbc.so.1.0.0*
-rw-r--r--  1 root root    239920 Aug  3  2018 librelic_ec.so
-rw-r--r--  1 root root    829378 Aug  3  2018 librelic_s.a
-rw-r--r--  1 root root    453100 Aug  3  2018 librelic_s_ec.a
-rw-r--r--  1 root root    430616 Aug  3  2018 librelic.so
-rw-r--r--  1 root root   1026972 Nov  3 23:11 libssl.a
lrwxrwxrwx  1 root root        13 Nov  3 23:11 libssl.so -> libssl.so.1.1*
-rwxr-xr-x  1 root root    684008 Nov  3 23:11 libssl.so.1.1*
-rw-r--r--  1 root root   1974962 Aug  3  2018 libzsym.a
drwxr-xr-x  3 root root      4096 Apr  9  2017 netscape/
drwxr-xr-x  2 root root      4096 Aug  3  2018 pkgconfig/
drwxrwsr-x  4 root staff     4096 Dec  4 20:47 python2.7/
drwxrwsr-x  3 root staff     4096 Jul 20  2016 python3.5/
```

Any suggestions?

**Pull request merged**
